param(
    [string]$AgentRoot = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = "Continue"
$requiredFailures = [System.Collections.Generic.List[string]]::new()
$warnings = [System.Collections.Generic.List[string]]::new()

function Test-RequiredPath([string]$RelativePath) {
    $path = Join-Path $AgentRoot $RelativePath
    if (Test-Path -LiteralPath $path) {
        Write-Output "OK       $RelativePath"
    } else {
        Write-Output "FAIL     $RelativePath"
        $requiredFailures.Add($RelativePath)
    }
}

function Test-RequiredText([string]$RelativePath, [string]$Term) {
    $path = Join-Path $AgentRoot $RelativePath
    $content = [System.IO.File]::ReadAllText($path, [System.Text.UTF8Encoding]::new($false))
    if ($content -match [regex]::Escape($Term)) {
        Write-Output "OK       $RelativePath : $Term"
    } else {
        Write-Output "FAIL     $RelativePath : $Term"
        $requiredFailures.Add("$RelativePath semantik sozlesme eksik: $Term")
    }
}

function Test-ForbiddenText([string]$RelativePath, [string]$Term) {
    $path = Join-Path $AgentRoot $RelativePath
    $content = [System.IO.File]::ReadAllText($path, [System.Text.UTF8Encoding]::new($false))
    if ($content -match [regex]::Escape($Term)) {
        Write-Output "FAIL     $RelativePath : eski ifade $Term"
        $requiredFailures.Add("$RelativePath eski semantik ifade iceriyor: $Term")
    } else {
        Write-Output "OK       $RelativePath : eski ifade yok"
    }
}

Write-Output "Marketing Agent Codex healthcheck"
Write-Output "Agent root: $AgentRoot"
Write-Output ""

Write-Output "[Required release structure]"
@(
    "AGENTS.md", "ARCHITECTURE.md", "SKILLS.md", "agents", "pipelines", "skills",
    "scripts", "scripts\reconcile-workspace-state.ps1", "templates", "mcps.json", "agent-version.json", "release-manifest.json"
) | ForEach-Object { Test-RequiredPath $_ }

Write-Output ""
Write-Output "[JSON]"
foreach ($jsonName in @("mcps.json", "agent-version.json", "release-manifest.json")) {
    $path = Join-Path $AgentRoot $jsonName
    try {
        [System.IO.File]::ReadAllText($path) | ConvertFrom-Json | Out-Null
        Write-Output "OK       $jsonName"
    } catch {
        Write-Output "FAIL     $jsonName : $($_.Exception.Message)"
        $requiredFailures.Add($jsonName)
    }
}

Write-Output ""
Write-Output "[Skills]"
$skillDirs = Get-ChildItem -LiteralPath (Join-Path $AgentRoot "skills") -Directory
$invalidSkills = 0
foreach ($skillDir in $skillDirs) {
    if (-not (Test-Path -LiteralPath (Join-Path $skillDir.FullName "SKILL.md")) -or
        -not (Test-Path -LiteralPath (Join-Path $skillDir.FullName "agents\openai.yaml"))) {
        Write-Output "FAIL     $($skillDir.Name)"
        $invalidSkills++
    }
}
if ($invalidSkills -eq 0) {
    Write-Output "OK       $($skillDirs.Count) skill, SKILL.md ve agents/openai.yaml mevcut"
} else {
    $requiredFailures.Add("$invalidSkills gecersiz skill")
}

Write-Output ""
Write-Output "[Behavior contracts]"
foreach ($term in @("Quick advisory", "Workspace task", "Pipeline mode", "Urgent tactical", "Assumption-led")) {
    Test-RequiredText "AGENTS.md" $term
    Test-RequiredText "agents\orchestrator.md" $term
}
foreach ($term in @("Codex + Google Drive", "approved create flow", "web app is deferred")) {
    Test-RequiredText "AGENTS.md" $term
}
Test-RequiredText "ARCHITECTURE.md" "Codex + Google Drive first"
Test-RequiredText "QUICKSTART.md" "create-evaluation.ps1"
Test-RequiredText "QUICKSTART.md" "create-project.ps1"
Test-RequiredText "agents\onboarding-guide.md" "Ilk 10 Dakika Marketer Yolculugu"
Test-RequiredText "agents\onboarding-guide.md" "Simdi ne yapmak istiyorsun?"
Test-RequiredText "AGENTS.md" "Kocak sadakatini takdir ediyor."
Test-RequiredText "agents\onboarding-guide.md" "Kocak sadakatini takdir ediyor."
Test-ForbiddenText "AGENTS.md" "Koçak sadakatini takdir ediyor."
Test-ForbiddenText "agents\onboarding-guide.md" "Koçak sadakatini takdir ediyor."
Test-RequiredText "pipelines\idea-to-prd.md" "Evaluation Workspace Output Paths"
Test-RequiredText "pipelines\idea-to-prd.md" "Project Workspace Output Paths"
Test-RequiredText "pipelines\idea-to-prd.md" "Marketer Fit Guidance is not the idea-value verdict"
foreach ($dayFile in @("pazartesi.md", "sali.md", "carsamba.md", "persembe.md", "cuma.md", "cumartesi.md", "pazar.md")) {
    Test-RequiredText "agents\schedule-coordinator.md" $dayFile
}
Test-ForbiddenText "AGENTS.md" "values generated by the web app"
foreach ($term in @("Idea Value Decision", "Marketer Fit Guidance", "Validation Unit By Sales Motion")) {
    Test-RequiredText "pipelines\idea-to-prd.md" $term
}
Test-RequiredText "agents\schedule-coordinator.md" "Workspace evidence"
Test-RequiredText "agents\schedule-coordinator.md" "Final publication or delivery"
Test-ForbiddenText "agents\orchestrator.md" "Revizyonla Tekrar"

Write-Output ""
Write-Output "[Marketer freedom and idea-value contracts]"
Test-RequiredText "AGENTS.md" "Marketer Freedom And Support Principle"
Test-RequiredText "AGENTS.md" "Marketer ozgurlugu"
Test-RequiredText "AGENTS.md" "Aslolan fikirdir"
Test-RequiredText "AGENTS.md" "Marketer uygulama rehberligi"
Test-RequiredText "AGENTS.md" "verdict degildir"
Test-RequiredText "AGENTS.md" "Yeni fikir degerlendirme workspace'i"
Test-RequiredText "AGENTS.md" "Yeni proje workspace'i"
Test-RequiredText "AGENTS.md" "Var olan evaluation/project workspace"
Test-RequiredText "agents\onboarding-guide.md" "Yanlis Klasorde Acilma Durumu"
Test-RequiredText "agents\onboarding-guide.md" "Sadece fikir/tartisma"
Test-RequiredText "agents\onboarding-guide.md" "fikrin kendisini kanitlarla degerlendirelim"
Test-RequiredText "agents\onboarding-guide.md" "marketer'in yerine proje karari vermez"
Test-RequiredText "agents\orchestrator.md" "marketer is the decision owner"
Test-RequiredText "agents\orchestrator.md" "execution guidance"
Test-RequiredText "agents\orchestrator.md" "not as the idea-value verdict"
Test-RequiredText "pipelines\idea-to-prd.md" "Idea Value Comes First"
Test-RequiredText "pipelines\idea-to-prd.md" "Aslolan fikirdir"
Test-RequiredText "pipelines\idea-to-prd.md" "Marketer Execution Guidance"
Test-RequiredText "pipelines\idea-to-prd.md" "### 5.2"
Test-RequiredText "pipelines\idea-to-prd.md" "Market Research"
Test-RequiredText "pipelines\idea-to-prd.md" "### 5.3"
Test-RequiredText "pipelines\idea-to-prd.md" "Idea Validation"
Test-RequiredText "pipelines\idea-to-prd.md" "### 5.4"
Test-RequiredText "pipelines\idea-to-prd.md" "Realist Decision Discussion"
Test-RequiredText "pipelines\idea-to-prd.md" "### 5.5"
Test-RequiredText "pipelines\idea-to-prd.md" "ciktilar/marketer-uygulama-rehberligi.md"
Test-RequiredText "pipelines\idea-to-prd.md" "03-strateji/dogrulama/marketer-uygulama-rehberligi.md"
Test-RequiredText "..\mvp\mvp.md" "Post-MVP Appendix"
Test-RequiredText "..\mvp\mvp.md" "web app/PWA"
Test-RequiredText "..\mvp\mvp.md" "ilk product fazi icin runtime gereksinimi degildir"
Test-RequiredText "..\mvp\mvp.md" "Workspace artifact'i gorevi acikca kanitliyorsa"
Test-ForbiddenText "pipelines\idea-to-prd.md" "User Marketing Advantage"

Write-Output ""
Write-Output "[Optional local capabilities]"
if (Get-Command node -ErrorAction SilentlyContinue) {
    Write-Output "AVAILABLE node $(node --version)"
} else {
    Write-Output "OPTIONAL  Node.js bulunamadi; app-store MCP yerel calistirilamaz."
    $warnings.Add("Node.js")
}

$python = Get-Command python -ErrorAction SilentlyContinue
if ($python) {
    Write-Output "AVAILABLE $(& python --version 2>&1)"
} else {
    Write-Output "OPTIONAL  Python PATH uzerinde bulunamadi; Python yardimci scriptleri calistirilamaz."
    $warnings.Add("Python")
}

$appStoreServer = Join-Path $AgentRoot "vendor\mcp-appstore\server.js"
if (Test-Path -LiteralPath $appStoreServer) {
    Write-Output "AVAILABLE optional app-store MCP payload"
} else {
    Write-Output "OPTIONAL  app-store MCP vendor payload'i yok; web veya manuel fallback kullanilir."
    $warnings.Add("app-store MCP")
}

Write-Output ""
if ($requiredFailures.Count -gt 0) {
    Write-Output "SONUC: BASARISIZ - $($requiredFailures.Count) zorunlu sorun."
    exit 1
}

Write-Output "SONUC: HAZIR - zorunlu release yapisi gecerli; $($warnings.Count) opsiyonel capability uyarisi."
exit 0
